language: node_js
node_js:
  - '10'

script:
  - cp -r react-360-keyboard/static_assets/ static_assets/react-360-keyboard/
  - yarn bundle
  - mv static_assets build/static_assets

deploy:
  local-dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
